#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[UPDATING HOSTS]${normal}"
cp /etc/hosts.bak /tmp/hosts
curl https://raw.githubusercontent.com/voltamage/common/master/tmp/hosts -# >> /tmp/hosts
sudo mv /tmp/hosts /etc/hosts

echo ""
echo "${bold}[REVIEW]${normal}"
echo "${bold}[Review /etc/hosts]${normal}"
echo "[Hosts]"
cat /etc/hosts

echo ""
echo "${bold}[DONE]${normal}"
